version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # RabbitMQ management UI port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
